### ISSUE TITLE
 java.lang.NoClassDefFoundError: net/md_5/specialsource/transformer/MappingTransformer

### ISSUE THREAD

**Issue by vedisdragon** [md-5/SpecialSource#43]
Summary:
- I have a plugin that works with SpecialSource 1.7.4 but not 1.7 SNAPSHOT
- 1.7 SNAPSHOT works with my server but not with plugin
- 1.7.4 works with plugin but crashes my server

I'm trying to get Luckperms to work with Cauldron 1.7.10 and the suggested solution was to use SpecialSource 1.7.4 instead of the 1.7 SNAPSHOT I was on.
https://github.com/CyberdyneCC/Thermos/issues/498#issuecomment-247083549
I tried using SpecialSource 1.7.4 but I got this error:
java.lang.NoClassDefFoundError: net/md_5/specialsource/transformer/MappingTransformer
Crash report: https://drive.google.com/open?id=0B_vrOlC_nFXlU21NVHBVY010TTg

Additional info on Luckperms: https://www.spigotmc.org/threads/luckperms-an-advanced-permissions-plugin.174259/page-56#post-2481259

**Comment by md-5** [comment]
This is not an issue with SpecialSource, it is an issue with your server not supporting SpecialSource 1.7.4.
Since Cauldron is no longer maintained I don't think they will fix this.
